// SHARED
export const SET_LOADING = 'SET_LOADING'

// Auth
export const SET_AUTH_USER = 'SET_AUTH_USER'

// USERS
export const SET_USERS = 'SET_USERS'

export const CACHE_USER = 'CACHE_USER'

// CLIENTS
export const SET_INDIVIDUAL_CLIENTS = 'SET_INDIVIDUAL_CLIENTS'
export const ADD_INDIVIDUAL_CLIENT = 'ADD_INDIVIDUAL_CLIENT'
export const SET_CORPORATE_CLIENTS = 'SET_CORPORATE_CLIENTS'
export const ADD_CORPORATE_CLIENT = 'ADD_CORPORATE_CLIENT'
export const SET_ALL_CLIENTS = 'ADD_ALL_CLIENTS'
export const SET_SELECTED_CLIENT = 'SET_SELECTED_CLIENT'

// QUOTATIONS
export const SET_QUOTATIONS = 'SET_QUOTATIONS'
export const APPROVE_QUOTATION = 'APPROVE_QUOTATION'
export const SET_SELECTED_QUOTATION = 'SET_SELECTED_QUOTATION'
export const SET_SELECTED_RISK = 'SET_SELECTED_RISK'
export const SET_CURRENCY = 'SET_CURRENCY'
export const SET_HIGHEST_QUARTER = 'SET_HIGHEST_QUARTER'

// POLICIES
export const SET_POLICIES = 'SET_POLICIES'
export const ACTIVATE_POLICY = 'ACTIVATE_POLICY'
export const SET_SELECTED_POLICY = 'SET_SELECTED_POLICY'
export const SET_SELECTED_DEBIT_NOTE = 'SET_SELECTED_DEBIT_NOTE'
export const SET_SELECTED_CERTIFICATE = 'SET_SELECTED_CERTIFICATE'
export const SET_COVER_NOTES = 'SET_COVER_NOTES'

// RECEIPTS
export const SET_RECEIPTS = 'SET_RECEIPTS'
export const SET_SELECTED_RECEIPT = 'SET_SELECTED_RECEIPT'
export const CANCEL_RECEIPT = 'CANCEL_RECEIPT'
export const REINSTATE_RECEIPT = 'REINSTATE_RECEIPT'

// PRODUCTS
export const SET_PRODUCTS = 'SET_PRODUCTS'

// CLASSES
export const SET_CLASSES = 'SET_CLASSES'

// TRANSACTIONS
export const SET_TRANSACTIONS = 'SET_TRANSACTIONS'

// EXTERNAL SERVICES
export const SET_COUNTRIES = 'SET_COUNTRIES'
export const SET_COUNTRY_FLAG = 'SET_COUNTRY_FLAG'
export const SET_COUNTRY_CALLING_CODES = 'SET_COUNTRY_CALLING_CODES'
export const SET_COLORS = 'SET_COLORS'
export const ADD_COLOR = 'ADD_COLOR'
